apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.imagePullSecret.name }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{
    printf
    "{\"auths\":{\"%s\":{\"username\":\"%s\",\"password\":\"%s\",\"email\":\"%s\",\"auth\":\"%s\"}}}"
    .Values.dockerRegistry.server
    .Values.dockerRegistry.username
    .Values.dockerRegistry.password
    .Values.dockerRegistry.email
    (printf "%s:%s" .Values.dockerRegistry.username .Values.dockerRegistry.password | b64enc)
    | b64enc
  }}
